---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: "Test: file /etc/hosts"
      block:
        - name: "Stat file /etc/hosts"
          ansible.builtin.stat:
            path: "/etc/hosts"
          register: stat_etc_hosts

        - name: "Verify file /etc/hosts"
          ansible.builtin.assert:
            that:
              - stat_etc_hosts.stat.exists
              - stat_etc_hosts.stat.isreg
              - stat_etc_hosts.stat.pw_name == 'root'
              - stat_etc_hosts.stat.gr_name == 'root'

    - name: "Test: directory /tmp"
      block:
        - name: "Stat directory /etc/netplan"
          ansible.builtin.stat:
            path: "/etc/netplan"
          register: stat_etc_netplan

        - name: "Stat file /tmp/ansible-config.yaml"
          ansible.builtin.stat:
            path: "/tmp/ansible-config.yaml"
          register: stat_tmp_ansible_config_yml

        - name: "Slurp file /tmp/ansible-config.yaml"
          ansible.builtin.slurp:
            src: "/tmp/ansible-config.yaml"
          register: slurp_tmp_ansible_config_yml

        - name: "Verify directory /tmp/netplan"
          ansible.builtin.assert:
            that:
              - stat_etc_netplan.stat.exists
              - stat_etc_netplan.stat.isdir
              - stat_etc_netplan.stat.pw_name == 'root'
              - stat_etc_netplan.stat.gr_name == 'root'
              - stat_etc_netplan.stat.mode == '0755'
              - stat_tmp_ansible_config_yml.stat.exists
              - stat_tmp_ansible_config_yml.stat.isreg
              - stat_tmp_ansible_config_yml.stat.pw_name == 'root'
              - stat_tmp_ansible_config_yml.stat.gr_name == 'root'
              - stat_tmp_ansible_config_yml.stat.mode == '0644'
              - slurp_tmp_ansible_config_yml.content != ''
